/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LightsoutIndexRouteImport } from './routes/lightsout/index'
import { Route as IceIndexRouteImport } from './routes/ice/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LightsoutIndexRoute = LightsoutIndexRouteImport.update({
  id: '/lightsout/',
  path: '/lightsout/',
  getParentRoute: () => rootRouteImport,
} as any)
const IceIndexRoute = IceIndexRouteImport.update({
  id: '/ice/',
  path: '/ice/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ice': typeof IceIndexRoute
  '/lightsout': typeof LightsoutIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ice': typeof IceIndexRoute
  '/lightsout': typeof LightsoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ice/': typeof IceIndexRoute
  '/lightsout/': typeof LightsoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ice' | '/lightsout'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ice' | '/lightsout'
  id: '__root__' | '/' | '/ice/' | '/lightsout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IceIndexRoute: typeof IceIndexRoute
  LightsoutIndexRoute: typeof LightsoutIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lightsout/': {
      id: '/lightsout/'
      path: '/lightsout'
      fullPath: '/lightsout'
      preLoaderRoute: typeof LightsoutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ice/': {
      id: '/ice/'
      path: '/ice'
      fullPath: '/ice'
      preLoaderRoute: typeof IceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IceIndexRoute: IceIndexRoute,
  LightsoutIndexRoute: LightsoutIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
